# Generated by Django 3.0.5 on 2020-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(help_text='Fill in your member profile', null=True, upload_to='member_profile_pics'),
        ),
        migrations.AlterField(
            model_name='members',
            name='image1',
            field=models.ImageField(help_text='Fill in your identity card', null=True, upload_to='member_identity_pics'),
        ),
    ]
