# Generated by Django 3.0.5 on 2020-06-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200526_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-id']},
        ),
    ]
