# Generated by Django 3.0.5 on 2020-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200611_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
