# Generated by Django 3.0.5 on 2020-09-01 14:11

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200727_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='tel',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number e.g 2055667788-856', max_length=31, unique=True),
        ),
    ]
