# Generated by Django 3.0.5 on 2020-06-05 07:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='YY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, choices=[('CHANTHABULY', 'Chanthabuly'), ('SIKHOTTABONG', 'Sikhottabong'), ('XAYSETHA', 'Xaysetha'), ('SISATTANAK', 'Sisattanak'), ('XAYTHANY', 'Xaythany')], default='SISATTANAK', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, default='Vientiane Capital', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number e.g 0255667788-856', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
