# Generated by Django 3.0.5 on 2020-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='YY-MM-DD', null=True),
        ),
    ]
