# Generated by Django 3.0.5 on 2020-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, choices=[('ຈັນທະບູລິ', 'ຈັນທະບູລິ'), ('ສີໂຄດຕະບອງ', 'ສີໂຄດຕະບອງ'), ('ໄຊເສດຖາ', 'ໄຊເສດຖາ'), ('ສີສັດຕະນາກ', 'ສີສັດຕະນາກ'), ('ໄຊທານີ', 'ໄຊທານີ')], default='ຈັນທະບູລິ', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, default='ນະຄອນຫຼວງວຽງຈັນ', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('ຊາຍ', 'ຊາຍ'), ('ຍິງ', 'ຍິງ')], default='ຊາຍ', max_length=3, null=True),
        ),
    ]
