# Generated by Django 3.0.5 on 2020-06-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_checkoutborrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowbook',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='checkoutborrow',
            options={'ordering': ['id']},
        ),
    ]
