# Generated by Django 3.0.5 on 2020-06-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_auto_20200619_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutborrow',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrow.BorrowBook'),
        ),
    ]
