# Generated by Django 3.0.5 on 2020-06-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_auto_20200619_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutborrow',
            name='member',
        ),
    ]
