# Generated by Django 3.0.5 on 2020-06-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_auto_20200624_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutborrow',
            name='point',
        ),
    ]
