# Generated by Django 3.0.5 on 2020-06-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0010_auto_20200625_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='point',
        ),
    ]
