# Generated by Django 3.0.5 on 2020-06-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0015_auto_20200625_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutborrow',
            name='member',
        ),
    ]
