# Generated by Django 3.0.5 on 2020-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0016_remove_checkoutborrow_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutborrow',
            name='status',
            field=models.CharField(blank=True, choices=[('ຢືມປື້ມ', 'ຢືມປື້ມ'), ('ຄືນປື້ມ', 'ຄືນປື້ມ')], default='ຢືມປື້ມ', max_length=7, null=True),
        ),
    ]
