# Generated by Django 3.0.5 on 2020-07-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0017_checkoutborrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutborrow',
            name='status',
            field=models.CharField(choices=[('ຢືມປື້ມ', 'ຢືມປື້ມ'), ('ຄືນປື້ມ', 'ຄືນປື້ມ')], default='ຢືມປື້ມ', max_length=7),
        ),
    ]
