# Generated by Django 3.0.5 on 2020-07-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0019_reclaimbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_book', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrow.CheckOutBorrow')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
