# Generated by Django 3.0.5 on 2020-05-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={'ordering': ['-id']},
        ),
    ]
