# Generated by Django 3.0.5 on 2020-05-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject_heading', models.CharField(max_length=50)),
                ('primary_author', models.CharField(max_length=20)),
                ('coauthor', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('page_element', models.CharField(max_length=4)),
                ('ISBN', models.CharField(max_length=20)),
                ('booktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktype.BookType')),
            ],
        ),
    ]
