# Generated by Django 3.0.5 on 2020-05-15 06:29

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', phone_field.models.PhoneField(blank=True, help_text='Contact phone number e.g 0255667788-856', max_length=31, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('village', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
            ],
        ),
    ]
