# Generated by Django 3.0.5 on 2020-05-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0003_bookstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='bookstore',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='booktype',
            options={'ordering': ['-id']},
        ),
    ]
