# Generated by Django 3.0.5 on 2020-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0005_book_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
