# Generated by Django 3.0.5 on 2020-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0006_book_original_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_language',
            field=models.CharField(max_length=20),
        ),
    ]
