# Generated by Django 3.0.5 on 2020-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0007_auto_20200619_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('ວ່າງ', 'ວ່າງ'), ('ຖືກຢືມ', 'ຖຶກຢືມ')], default='ວ່າງ', max_length=12, null=True),
        ),
    ]
