# Generated by Django 3.0.5 on 2020-07-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0010_auto_20200712_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='booktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktype.BookType'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coauthor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_element',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='primary_author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('ວ່າງ', 'ວ່າງ'), ('ຖືກຢືມ', 'ຖຶກຢືມ')], default='ວ່າງ', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
