# Generated by Django 3.0.5 on 2020-07-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0011_auto_20200715_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booktype.BookStore'),
        ),
    ]
