# Generated by Django 3.0.5 on 2020-09-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktype', '0014_auto_20200823_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookstore',
        ),
    ]
